# Makefile for the focaltech touchscreen drivers.


obj-$(CONFIG_TOUCHSCREEN_FT5726)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FT5726)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FT5726)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FT5726)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FT5726)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FT5726)   +=  focaltech_point_report_check.o


obj-$(CONFIG_TOUCHSCREEN_FT5726)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FT5726)   +=  focaltech_flash/



obj-$(CONFIG_TOUCHSCREEN_FT5726)   +=  focaltech_i2c.o
